### ISSUE TITLE
[Presentation] CNF WG BoF at Open Networking and Edge Summit 

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/bestpractices#196]
**Title:**  CNF WG BoF: Bring Your Networking Challenge, We’ll Find a Cloud Native Best Practice 

**Speakers:** CNF WG Co-chairs, @iawells @jeffsaelens @taylor

**Event details:**
- Tuesday, October 12 • 12:00pm - 12:30pm PDT 
- https://sched.co/og1s

**Tasks:**
- [x] create presentation slide deck
- [x] outline of high level talking points
- [x] create shared meeting notes for attendees to contribute in a read/write way (in addition to verbally on zoom)
- [x] promote on cnf-wg mailing list 
- [x] promote on cnf-wg slack
- [x] promote on tug slack
- [x] promote on cnf-testsuite-dev slack 
- [x] promote by @cnfconformance twitter
- [x] upload pdf slide deck to https://sched.co/og1s

**Comment by lixuna** [comment]
Shared meeting notes for CNF WG BoF 
https://docs.google.com/document/d/1uuxF561CxgoRG4c9LgvSLP4ljftty3tyiCPbj7Ybn50/edit#heading=h.zer80fnehhzp
