### ISSUE TITLE
[Research] Brainstorm how to collaborate with Anuket

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/bestpractices#309]
# Research: 
- Brainstorm how to collaborate with Anuket 

## Short description:

Add ideas for how CNTI and Anuket can work together.

## Ideas for collaboration

- IDEA 1: Review anuket requirements for cloud native best practices and identify gaps that CNTI can fill
- IDEA 2: Review anuket requirements and test cases to identify missing tests that CNTI can fill
   - See https://github.com/cnti-testcatalog/testcatalog/issues/3
 - IDEA 3: Review Anuket ["4. Operational Runbook"](https://cntt.readthedocs.io/projects/ri2/en/stable-orinoco/chapters/chapter04.html#chapters-chapter04--page-root) and tests or tests ideas from the CNTI Test Catalog
   - See https://github.com/cnti-testcatalog/testsuite/issues/1716

### Tasks:

- [x] Analyze Anuket docs for foundational cloud native best practices
- [x]  Analyze CNTI Test Catalog for related tests
- [x]  Prepare a report to share with Anuket chairs
- [x] Schedule a call to review the findings - Review to be held in CNTI Best Practices meeting on Monday, March 11 at 8:30-9am PT

### Action items:
- [ ] tbd - create new issues for action items. 
- [ ] If action item is related to Best Practice, use https://github.com/lfn-cnti/bestpractices/issues/new/choose
- [ ] If action item is related to Certification, use https://github.com/lfn-cnti/certification/issues/new
- [ ] If action item is related to Test Catalog, use https://github.com/cnti-testcatalog/testsuite/issues/new

**Comment by lixuna** [comment]
IDEA 1: Review anuket requirements for cloud native best practices and identify gaps that CNTI can fill

### Tasks: 

- [x] Identify RA2 and RC2 references 
- [x] Add URLs for RA2 and RC2 references in a comment below
- [x] Analyze RA2 and RC2 docs for *foundational* cloud native best practices


IDEA 2: Review anuket requirements and test cases to identify missing tests that CNTI can fill

- [ ] Analyze CNTI Test Catalog for related tests 
- [ ] Prepare a report to share with Anuket chairs
- [ ] Schedule a time to meet with Anuket chairs

----

See

https://docs.google.com/document/d/1iXYVw5jdOMrzds64qAOYuf-x5kGE2oVzpaOrQZ05Xtc/edit

**Comment by Smitholi67** [comment]
RA2 specifications for Anuket Workloads:
https://cntt.readthedocs.io/projects/ra2/en/stable-orinoco/chapters/chapter04.html#kubernetes-workloads

RC2 Test Cases and Requirements for Anuket Workloads:  
https://cntt.readthedocs.io/projects/rc2/en/stable-orinoco/chapters/chapter04.html

**Comment by taylor** [comment]
For IDEA 2: Review anuket requirements and test cases to identify missing tests that CNTI can fill:

- [[Research] Identify existing tests in CNTI Test Catalog that are in alignment with Anuket requirements](https://github.com/cnti-testcatalog/testcatalog/issues/3)

See test catalog ticket for where this work is being done -> https://github.com/cnti-testcatalog/testcatalog/issues/3

**Comment by lixuna** [comment]
Analysis of RA2 and RC2 docs for foundational cloud native best practices started at https://docs.google.com/document/d/1iXYVw5jdOMrzds64qAOYuf-x5kGE2oVzpaOrQZ05Xtc/edit#heading=h.tmdrkdxp5hi4

**Comment by taylor** [comment]
IDEA 3: Review Anuket ["4. Operational Runbook"](https://cntt.readthedocs.io/projects/ri2/en/stable-orinoco/chapters/chapter04.html#chapters-chapter04--page-root) and tests or tests ideas from the CNTI Test Catalog

See https://github.com/cnti-testcatalog/testsuite/issues/1716

**Comment by lixuna** [comment]
Thur, Feb 29 - slack message with [analysis](https://docs.google.com/document/d/1iXYVw5jdOMrzds64qAOYuf-x5kGE2oVzpaOrQZ05Xtc/edit#heading=h.tmdrkdxp5hi4) was sent to Anuket team

**Comment by lixuna** [comment]
CNTI V2.0 List of Essential Tests was reviewed in the CNTI Certification call on Thursday, March 14, 2024 at 9am PT

Community Approval for [V2.0 CNTI](https://docs.google.com/document/d/1ysgGfiG2qEXJUyxksVnuzSeKTcp9V5-SId65_nwDRDg/edit) Certification Tests was granted.

We will move forward with the process of updating the list of essential tests to include additional tests that match Anuket RA2 specs
