### ISSUE TITLE
[Research] Brainstorm how to collaborate with Nephio

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/bestpractices#310]
# Research: 
- Brainstorm how to collaborate with Nephio 

## Short description:
- Review Nephio requirements/specs for cloud native best practices

### Tasks: 

- [ ] Identify Nephio references 
- [ ] Add URLs for Nephio references in a comment below
- [ ] Analyze Nephio docs for *foundational* cloud native best practices
- [ ] Analyze CNTI Test Catalog for related tests 
- [ ] Prepare a report to share with Nephio chairs
- [ ] Schedule a time to meet with Nephio chairs

**Comment by lixuna** [comment]
SIG Network Architecture meeting on [Mondays](https://docs.google.com/document/d/1DsGvc6OIdC853eUQJlNS17RLY1Zh0BlyUEZqvCALZOQ/edit#heading=h.sr617x3j8yhh) at 10am PT

This [document](https://docs.google.com/document/d/1jSa3sxM2X9CPKUbNiPwOBDsSws1sQHS93c2e7KCu00c/edit#heading=h.ihhuoulth6fe) contains information about the existing requirements. 

Nephio RxScope at: https://github.com/orgs/nephio-project/projects/12/views/2?pane=issue&itemId=51686058

**Comment by lixuna** [comment]
@electrocucaracha Can you suggest any additional Nephio references that we should review?
