### ISSUE TITLE
[Research] Brainstorm how to collaborate with Project Sylva

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/bestpractices#311]
# Research: 
- Brainstorm how to collaborate with Project Sylva 

## Short description:
- Review Project Sylva requirements/specs for cloud native best practices

### Tasks: 

- [ ] Identify Project Sylva references 
- [ ] Add URLs for Project Sylva references in a comment below
- [ ] Analyze Project Sylva docs for *foundational* cloud native best practices
- [ ] Analyze CNTI Test Catalog for related tests 
- [ ] Prepare a report to share with Project Sylva chairs
- [ ] Schedule a time to meet with Project Sylva chairs

**Comment by pensarguet** [comment]
hi @lixuna , 
Here are the core references for Sylva with Web page (https://sylvaproject.org/) and gitlab root entry (https://gitlab.com/sylva-projects). I will ping Guillaume Nevicato and team to liaise with you. 
Please note that there will be a Sylva Dev Day March 19, in Orange Innovation Office, the day before kubecon EU in Paris. 
For Foundational Cloud Native Best practices, we could ask to the TSC. For the Test lab, the WG lead is Luis Velarde from TEF. Guillaume is the right person to set a joint meeting. Ping me if you need his contact.

**Comment by lixuna** [comment]
FYI - Sylva TSC Meeting Minutes - 07th of Febr 2024
- https://gitlab.com/sylva-projects/governance/-/wikis/2024-TSC-Minutes/02-07-TSC
- as of Sylva v1, k8s 1.27 will be the version used in workload clusters, CNF vendor must be compatible with this version
- [Sylva Dev Day 2024 - Registration Form](https://docs.google.com/forms/d/e/1FAIpQLSez4QqODmVPKxEaDKtZro20L0XBLuK1NT1rXUrFD4FkoFsFWg/viewform)
