### ISSUE TITLE
[General] start the LFN Project induction process for CNTI

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/bestpractices#322]
**Describe the update:**
- In the LFN TAC meeting on Wed, Feb 7, the TAC requested the CNTI community to start the LFN Project induction process
- https://wiki.lfnetworking.org/display/LN/Getting+Started+With+LFN 

**Describe why update is needed**
- CNF WG (and CNCF’s related Cloud Native Telco efforts) has moved to LFN (see [wiki](https://wiki.lfnetworking.org/display/LN/Cloud+Native+Telecom+Networking+Initiative))
- LFN prefers to have all efforts under their Project structure

**Tasks:**

- [ ] Review https://wiki.lfnetworking.org/display/LN/Getting+Started+With+LFN
- [ ] Review https://wiki.lfnetworking.org/display/LN/How+to+Join+the+LFN+as+a+Project
- [ ] Start [Project Proposal](https://wiki.lfnetworking.org/display/LN/Project+Proposals)
- [ ] tba
