### ISSUE TITLE
[Research] Review CSP Whitepaper and identify cloud native best practices 

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/bestpractices#323]
# Research: 
- Review CSP Whitepaper and identify cloud native best practices 

## Short description:
- Review [CSP Whitepaper](https://www.cloud-native-telecom.org/whitepapers/Accelerating%20Cloud%20Native%20in%20Telco.pdf)  
-  identify cloud native best practices 
- Create new issues in this Github repo for each, individual best practice idea https://github.com/lfn-cnti/bestpractices/issues/new/choose
- Follow Best Practice Progress in the new issues, https://github.com/lfn-cnti/bestpractices/blob/main/doc/cbpps/cnf_best_practice_process.md - one per best practice

### Tasks: 

- [ ] Review [CSP Whitepaper and identify cloud native best practices ](https://www.cloud-native-telecom.org/whitepapers/Accelerating%20Cloud%20Native%20in%20Telco.pdf)
- [ ] Create new issues in this Github repo for each, individual best practice idea https://github.com/lfn-cnti/bestpractices/issues/new/choose
- [ ] Follow Best Practice Progress in new issue, https://github.com/lfn-cnti/bestpractices/blob/main/doc/cbpps/cnf_best_practice_process.md
