### ISSUE TITLE
[Research] Brainstorm how to collaborate with NGMN (Cloud Native Manifesto)

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/bestpractices#335]
# Research: 
- Brainstorm how to collaborate with NGMN (Cloud Native Manifesto) 

## Short description:
- Collaboration with NGMN to help with high-level CNTI goals 
- Increase participation and voice of CSPs

### Tasks: 
- [x] Schedule a CNTI Introduction with NGMN chairs
- [x] Identify NGMN references 
- [x] Add URLs for NGMN references in a comment below
- [ ] Analyze NGMN docs for *foundational* cloud native best practices
- [ ] Analyze CNTI Test Catalog for related tests 
- [ ] Prepare a report to share with NGMN chairs

**Comment by lixuna** [comment]
NGMN - CNTI Introductions
- held on Thursday, March 7⋅9:00 – 9:45am CT

**Comment by lixuna** [comment]
References: 
- https://www.ngmn.org/highlight/ngmn-publishes-cloud-native-manifesto.html
- https://www.ngmn.org/wp-content/uploads/NGMN_Cloud_Native_Manifesto.pdf
- https://www.cncf.io/blog/2023/12/13/announcing-the-accelerating-cloud-native-in-telco-whitepaper-v1/
- https://www.cloud-native-telecom.org/whitepapers/Accelerating%20Cloud%20Native%20in%20Telco.pdf

**Comment by Smitholi67** [comment]
@taylor @lixuna - I propose that we reach out to NGMN as a follow-up to our first meeting.  We can suggest a discussion on how collaboration with CNTI can help to create links/linkage from NGMN cloud native manifesto and WP to the best practice tests in the Test Catalog.  Additionally, we could discuss ambitions they might have with certification and perhaps we should also address Syva certification.  I believe NGMN is actively supporting Sylva.  We will want to highlight how we compliment/differ and work to identify what we have as mutual interests.

**Comment by lixuna** [comment]
Mar 26 - update, follow-up email was sent by @Smitholi67 to NGMN contacts
